Dev-tanay/Rubik-Cube

README.md
Here are the enhancements and changes made from the previous `README.md`:
1. **Badges Added**:
- Included badges for the latest GitHub release, issues, forks, stars, license, and website status at the top of the `README.md`. These badges provide a quick overview of the project's status and engagement on GitHub.
2. **HTML Structure**:
- Replaced Markdown headings with HTML tags for `<h1>`, `<h2>`, and `<h3>` to maintain consistency with the HTML format used in the document.
- Used `<p>` tags for paragraphs to ensure proper spacing and readability.
3. **List Formatting**:
- Used `<ul>` and `<li>` tags for unordered lists (e.g., the visible part of the cube pieces).
- Used `<ol type="i">` and `<li>` tags for ordered lists with Roman numerals for the "How to Play" and "Installation" sections. …
=> New Badges are added in Readme and enhanced

.github/ISSUE TEMPLATE/Bug_report_template.md, .github/ISSUE TEMPLATE/Feature_request_template.md
Added a Issue Template.
Fixes: #127 
@Dev-tanay Kindly review and merge this PR under GSSoC '24 and also add the required labels to it.
Thank you!
=> Fixes #127

index.html, script1.js, style.css
Fixes #104 
This PR fixes the issue #104 raised by me - Ritankar Saha regarding the addition of the Google Login/SIgnin. This ensures that the user can easily google login into the website thereby enhancing the feature and personalisation of the website.
I have followed the CONTRIBUTION GUIDELINES.
I have self reviewed my code.
**_I have commented all my code, particularly in hard-to-understand areas._**
**_My changes generates no new warnings._**
This is how the google login button looks like. And on clicking the google login button, it shows the default option to continue as the person, thereby enhancing feasibility. After that it logs into the home page of the website.
This is how it looks.
**_The website will also work even if the user does not logs into the website._**
Fixes #104
=> Adding the Google Login/Sign-in to the webpage - Ritankar_Saha Fixes 

CODE_OF_CONDUCT.md
=> doc:  add CODE_OF_CONDUCT.MD File

index.html, script.js, style.css
- **Button** - Changed padding and size and added a hover effect of changing the color of the button which makes the button more prominent now. 
- **Back-button** - moved the back button from bottom left to top left to make it more prominently visible and easy to use (especially for mobile users).
- **Leaderboard** - Removed the tap twice feature to revert back to main screen and instead a back button which can be used to navigate to the main screen.
=> Fixed button UI and leaderboard navigation

.github/Pull-request_template.yml
This adds a Pull Request (PR) template to the PRs raised in this repository.
Fixes #133 
@Dev-tanay Kindly review and merge this PR.
Also, kindly add "gssoc" and "Level1/2/3" label to this.
Thank you!
=> Fixes #133

.github/ISSUE TEMPLATE/Bug_report_template.md, .github/ISSUE TEMPLATE/Feature_request_template.md, .github/ISSUE TEMPLATE/docs.md
Updated Issue template and also added new docs template.
Fixes:  #89 
- [  ] Bug fix (non-breaking change which fixes an issue)
- [  ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [  ] This change requires a documentation update
=> Docs: added issue template

.github/Pull-request_template.yml, script.js
Added a return to home option after the user has completed the challenge.
Fixes:  #201 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have made this from my own
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
=> Adding Try Again Option #201

index.html, style.css
Removed the duplicate info button
Before: 
Now:
=> Removed the duplicate info button

AboutUs/About.html
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes:  #(issue no.)
=> Dynamic Copyright Year Done

index.html, script.js, style.css
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes:  #238
#screen shots
=> BACKGROUND THEME CHANGE

README.md, script.js
Added shortcut keys for moves and rotation. As well as pause(P) button for pause and resume for the game.
Fixes:  #250
=> Added keys for moves(R,L,U,D,B,F) and rotation (arrow keys)

check-progress.html, progress.css, progress.js
Dummy values in the check progress page were corrected and an additional alert was added to ask the user to play at least once to display the progress.
Fixes:  #312
=> Dummy values in check progress page corrected

check-progress.html, index.html
Removed Exit from the dropdown in index.html as it is unnecessary due to a pre-existing reset button. Fixed the exit button in check progress page.
Fixes:  #318
=> Exit button fixed

index.html
Removed setting option from Profile icon section
Fixes:  #331
Before:
After:
=> Update 2 settings Option

.vscode/settings.json, profile.css, progress.css
In this PR, we’ve given our login page and progress a fresh makeover! Here’s what’s changed:
Visual Enhancements:
Fixes:  #314
=> Updated profile page

index.html, script.js, style.css
I have fixed the responsiveness issue the application had in mobile resolutions. I also fixed the issue ( #[339](https://github.com/Dev-tanay/Rubik-Cube/issues/339) ) of the website not working as I had to do it to fix my issue. 
Fixes:  #323
=> fixed responsiveness and also fixed the website not working

AboutUs/About.css
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes:  #(issue no.) #324
**If it's not good, please assign me again I will do it better**
=> [Feature] Add Styles on Scrollbar in About page

AboutUs/About.css, AboutUs/About.html
Added social media icons to the website's footer section.
Made the buttons responsive also.
Fixes:  #328
New feature 
- [ X] I have made this from my own
- [X ] My code follows the style guidelines of this project
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
https://github.com/Dev-tanay/Rubik-Cube/assets/168854094/aca326df-b0c5-4403-a3ed-a2e0f642e176
Also made it responsive,
=> Added Social Media icons

check-progress.html, progress.css
Now the progress page matches to the theme of website,
make proper navigation,
It also matches with the edit profile page theme
Fixes:  #349
Before:
After:
https://github.com/Dev-tanay/Rubik-Cube/assets/168854094/9f518fda-89e3-4878-9462-dcc02481373e
=> Improved UI to match website theme

style.css
The profile icon and music button are now visible. I changed the positioning of these 2 buttons and the dropdown.
Fixes:  #344
=> Profile icon and music button now visible

index.html, profile.css
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes:  #314
=> change some text and color

check-progress.html, index.html
in check-progress.html the about us page was not inked correctly. 
Fixes:  #360
=> Edit: the about us page linked correctly

Dockerfile, deployment.yaml, service.yaml
I add the kubernetes and docker file through which you can deploy your app locally and also run your app locally
Fixes:  #(issue no.)
#362
=> add dockerfile and kubernetes file
